// src/list_of_ast_node_classes_define.hpp

#define LIST_OF_AST_NODE_CLASSES(X) \
	X(NodeBase, Base) \
	X(NodeList, List) \
	X(NodeProgram, Program) \
	X(NodePackage, Package) \
	X(NodeScopePackage, ScopePackage) \
	X(NodeModule, Module) \
	X(NodeScopeModproc, ScopeModproc) \
	X(NodeParamArgTypeSublist, ParamArgTypeSublist) \
	X(NodeArgPortSublist, ArgPortSublist) \
	X(NodeParamArgVarSublist, ParamArgVarSublist) \
	X(NodeParamModuleSublist, ParamModuleSublist) \
	X(NodeParamList, ParamList) \
	X(NodeArgList, ArgList) \
	X(NodeLeftRightBase, LeftRightBase) \
	X(NodeIdentTerminal, IdentTerminal) \
	X(NodeIdentMemberAccess, IdentMemberAccess) \
	X(NodeIdentScopeAccess, IdentScopeAccess) \
	X(NodeCall, Call) \
	X(NodeIdentEtc, IdentEtc) \
	X(NodeNumExpr, NumExpr) \
	X(NodeSizedNumExpr, SizedNumExpr) \
	X(NodeBracketPair, BracketPair) \
	X(NodeParenPair, ParenPair) \
	X(NodeHasString, HasString) \
	X(NodeIdent, Ident) \
	X(NodeConstString, ConstString) \
	X(NodeScopeBehav, ScopeBehav) \
	X(NodeEnum, Enum) \
	X(NodeScopeEnum, ScopeEnum) \
	X(NodeClass, Class) \
	X(NodeScopeClass, ScopeClass) \
	X(NodeExtends, Extends) \
	X(NodeMemberCallable, MemberCallable) \
	X(NodeUnion, Union) \
	X(NodeScopeUnion, ScopeUnion) \
	X(NodeParamPossibleTypename, ParamPossibleTypename) \
	X(NodeNoParamPossibleTypename, NoParamPossibleTypename) \
	X(NodeTypeof, Typeof) \
	X(NodeTypeRange, TypeRange) \
	X(NodeRangeSuffix, RangeSuffix) \
	X(NodeAuto, Auto) \
	X(NodeVoid, Void) \
	X(NodeUwire, Uwire) \
	X(NodeSwire, Swire) \
	X(NodeUbit, Ubit) \
	X(NodeSbit, Sbit) \
	X(NodeUbyte, Ubyte) \
	X(NodeSbyte, Sbyte) \
	X(NodeUshortint, Ushortint) \
	X(NodeSshortint, Sshortint) \
	X(NodeUint, Uint) \
	X(NodeSint, Sint) \
	X(NodeUlongint, Ulongint) \
	X(NodeSlongint, Slongint) \
	X(NodeSelf, Self) \
	X(NodePosParamArgInstList, PosParamArgInstList) \
	X(NodeNamedParamArgInstList, NamedParamArgInstList) \
	X(NodeOneParamArgInst, OneParamArgInst) \
	X(NodeExprBase, ExprBase) \
	X(NodeBinopExprBase, BinopExprBase) \
	X(NodeUnopExprBase, UnopExprBase) \
	X(NodeBinopExprLogAnd, BinopExprLogAnd) \
	X(NodeBinopExprLogOr, BinopExprLogOr) \
	X(NodeBinopExprCmpEq, BinopExprCmpEq) \
	X(NodeBinopExprCmpNe, BinopExprCmpNe) \
	X(NodeBinopExprCmpLt, BinopExprCmpLt) \
	X(NodeBinopExprCmpGt, BinopExprCmpGt) \
	X(NodeBinopExprCmpLe, BinopExprCmpLe) \
	X(NodeBinopExprCmpGe, BinopExprCmpGe) \
	X(NodeBinopExprPlus, BinopExprPlus) \
	X(NodeBinopExprMinus, BinopExprMinus) \
	X(NodeBinopExprMul, BinopExprMul) \
	X(NodeBinopExprDiv, BinopExprDiv) \
	X(NodeBinopExprMod, BinopExprMod) \
	X(NodeBinopExprBitAnd, BinopExprBitAnd) \
	X(NodeBinopExprBitOr, BinopExprBitOr) \
	X(NodeBinopExprBitXor, BinopExprBitXor) \
	X(NodeBinopExprBitLsl, BinopExprBitLsl) \
	X(NodeBinopExprBitLsr, BinopExprBitLsr) \
	X(NodeBinopExprBitAsr, BinopExprBitAsr) \
	X(NodeUnopExprLogNot, UnopExprLogNot) \
	X(NodeUnopExprBitNot, UnopExprBitNot) \
	X(NodeUnopExprPlus, UnopExprPlus) \
	X(NodeUnopExprMinus, UnopExprMinus) \
	X(NodeUnopExprDollarUnsigned, UnopExprDollarUnsigned) \
	X(NodeUnopExprDollarSigned, UnopExprDollarSigned) \
	X(NodeUnopExprDollarIsUnsigned, UnopExprDollarIsUnsigned) \
	X(NodeUnopExprDollarIsSigned, UnopExprDollarIsSigned) \
	X(NodeUnopExprDollarRange, UnopExprDollarRange) \
	X(NodeUnopExprDollarRevrange, UnopExprDollarRevrange) \
	X(NodeUnopExprDollarSize, UnopExprDollarSize) \
	X(NodeUnopExprDollarFirst, UnopExprDollarFirst) \
	X(NodeUnopExprDollarLast, UnopExprDollarLast) \
	X(NodeUnopExprDollarHigh, UnopExprDollarHigh) \
	X(NodeUnopExprDollarLow, UnopExprDollarLow) \
	X(NodeUnopExprDollarClog2, UnopExprDollarClog2) \
	X(NodeBinopExprDollarPow, BinopExprDollarPow) \
	X(NodePseudoExprDollarBase, PseudoExprDollarBase) \
	X(NodePseudoExprDollarPast, PseudoExprDollarPast) \
	X(NodePseudoExprDollarStable, PseudoExprDollarStable) \
	X(NodePseudoExprDollarRose, PseudoExprDollarRose) \
	X(NodePseudoExprDollarFell, PseudoExprDollarFell) \
	X(NodePseudoExprDollarGlobalClock, PseudoExprDollarGlobalClock) \
	X(NodeUnopExprTypeof, UnopExprTypeof) \
	X(NodeCatExpr, CatExpr) \
	X(NodeListCat, ListCat) \
	X(NodeReplExpr, ReplExpr) \
	X(NodeRangeExprAny, RangeExprAny) \
	X(NodeRangeOne, RangeOne) \
	X(NodeRangeTwo, RangeTwo) \
	X(NodeStmtList, StmtList) \
	X(NodeAnyForStmt, AnyForStmt) \
	X(NodeForStmt, ForStmt) \
	X(NodeGenerateForStmt, GenerateForStmt) \
	X(NodeIfStmt, IfStmt) \
	X(NodeGenerateIfStmt, GenerateIfStmt) \
	X(NodeWhileStmt, WhileStmt) \
	X(NodeBehavAssignStmt, BehavAssignStmt) \
	X(NodeContAssignStmt, ContAssignStmt) \
	X(NodeMemberAccessPublicStmt, MemberAccessPublicStmt) \
	X(NodeMemberAccessProtectedStmt, MemberAccessProtectedStmt) \
	X(NodeMemberAccessPrivateStmt, MemberAccessPrivateStmt) \
	X(NodeSwitchStmt, SwitchStmt) \
	X(NodeSwitchzStmt, SwitchzStmt) \
	X(NodeExprCaseItem, ExprCaseItem) \
	X(NodeDefaultCaseItem, DefaultCaseItem) \
	X(NodeScopeSwitch, ScopeSwitch) \
	X(NodeUsingStmt, UsingStmt) \
	X(NodeInstModuleStmt, InstModuleStmt) \
	X(NodeReturnStmt, ReturnStmt) \
	X(NodeDollarResizeStmt, DollarResizeStmt) \
	X(NodeInitialBlock, InitialBlock) \
	X(NodeAlwaysCombBlock, AlwaysCombBlock) \
	X(NodeAlwaysBlkBlock, AlwaysBlkBlock) \
	X(NodeAlwaysFfBlock, AlwaysFfBlock) \
	X(NodeAssertStmt, AssertStmt) \
	X(NodeAssumeStmt, AssumeStmt) \
	X(NodeCoverStmt, CoverStmt) \
	X(NodeRestrictStmt, RestrictStmt) \
	X(NodeStaticAssertStmt, StaticAssertStmt) \
	X(NodePosedgeInst, PosedgeInst) \
	X(NodeNegedgeInst, NegedgeInst) \
	X(NodeEdgeList, EdgeList) \
	X(NodeDeclCallable, DeclCallable) \
	X(NodeDeclFunc, DeclFunc) \
	X(NodeDeclProc, DeclProc) \
	X(NodeDeclTask, DeclTask) \
	X(NodeIdentTermEqualsExtra, IdentTermEqualsExtra) \
	X(NodeIdentTermEqualsExtraList, IdentTermEqualsExtraList) \
	X(NodeDeclConstList, DeclConstList) \
	X(NodeDeclVarList, DeclVarList) \
	X(NodeModport, Modport) \
	X(NodeModportSubList, ModportSubList) \
	X(NodeIdentList, IdentList) \

